export const USER_FETCH_START = "USER_FETCH_START";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAIL = "USER_FETCH_FAIL";

export const SIGN_OUT = "SIGN_OUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";

export const ADD_ARTISTS_START = "ADD_ARTISTS_START";
export const ADD_ARTISTS_SUCCESS = "ADD_ARTISTS_SUCCESS";
export const ADD_ARTISTS_FAIL = "ADD_ARTISTS_FAIL";

export const ADD_ALBUMS_START = "ADD_ALBUMS_START";
export const ADD_ALBUMS_SUCCESS = "ADD_ALBUMS_SUCCESS";
export const ADD_ALBUMS_FAIL = "ADD_ALBUMS_FAIL";

export const FETCH_ARTISTS_SONGS_START = "FETCH_ARTISTS_SONGS_START";
export const FETCH_ARTISTS_SONGS_SUCCESS = "FETCH_ARTISTS_SONGS_SUCCESS";
export const FETCH_ARTISTS_SONGS_FAIL = "FETCH_ARTISTS_FAIL";

export const SET_USER_THEME_START = "SET_USER_THEME_START";
export const SET_USER_THEME_SUCCESS = "SET_USER_THEME_SUCCESS";
export const SET_USER_THEME_FAIL = "SET_USER_THEME_FAIL";

export const FETCH_USER_THEME_START = "FETCH_USER_THEME_START";
export const FETCH_USER_THEME_SUCCESS = "FETCH_USER_THEME_SUCCESS";
export const FETCH_USER_THEME_FAIL = "FETCH_USER_THEME_FAIL";

export const FETCH_ALBUM_SONGS_START = "FETCH_ALBUM_SONGS_START";
export const FETCH_ALBUM_SONGS_SUCCESS = "FETCH_ALBUM_SONGS_SUCCESS";
export const FETCH_ALBUM_SONGS_FAIL = "FETCH_ALBUM_SONGS_FAIL";

export const PAUSE_SONG = "PAUSE_SONG";
export const PLAY_SONG = "PLAY_SONG";
